baseurl = "https://www.zansara.dev"
title = "Sara Zan"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20

[markup.highlight]
style = "github-dark"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  navbar = "Home"
  author = "Sara Zan"
  info = """
  Lead AI Engineer at [Kwal](https://www.kwal.ai/),
  [main contributor](https://github.com/deepset-ai/haystack/graphs/contributors) of [Haystack](https://haystack.deepset.ai/), 
  former [CERN](https://home.cern/) employee. 
  I'm also an opinionated sci-fi reader, hiker, tinkerer and somewhat polyglot. Currently busy trying to learn Portuguese and Hungarian at the same time.
  """
  description = "Sara Zan's Personal Website"
  keywords = "blog,developer,personal,python,llm,nlp,swe,software-engineering,open-source"
  avatarurl = "/me/avatar-color.svg"
  
  #gravatar = "john.doe@example.com"

  faviconSVG = "/favicon.svg"
  favicon_32 = "/favicon.png"
  touchicon = "/favicon.png"
  # favicon_16 = "/img/favicon-16x16.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/ZanSara/"
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/sarazanzottera"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 1
  url = "https://twitter.com/zansara_dev"
[[params.social]]
  name = "Mastodon"
  icon = "fa fa-brands fa-mastodon fa-2x"
  weight = 1
  url = "https://mastodon.social/@zansara"
[[params.social]]
  name = "Y Combinator"
  icon = "fa fa-y-combinator-square fa-2x"
  weight = 1
  url = "https://news.ycombinator.com/user?id=zansara"
[[params.social]]
  name = "Stackoverflow"
  icon = "fa fa-stack-overflow fa-2x"
  weight = 1
  url = "https://stackoverflow.com/users/19108168/zansara"
[[params.social]]
  name = "Google Scholar"
  icon = "fa fa-graduation-cap fa-2x"
  weight = 1
  url = "https://scholar.google.com/citations?hl=en&user=IsXR9HAAAAAJ"
[[params.social]]
  name = "Email"
  icon = "fa fa-envelope fa-2x"
  weight = 1
  url = "mailto:blog@zansara.dev"
[[params.social]]
  name = "RSS"
  icon = "fa fa-rss fa-2x"
  weight = 1
  url = "/index.xml"
[[params.social]]
  name = "Substack"
  icon = "fa fa-bookmark fa-2x"
  weight = 1
  url = "https://zansara.substack.com/"

# [taxonomies]
#   tag = "tags"
#   series = "series"

# Menu links
[[menu.main]]
  name = "About"
  weight = 1
  url = "about"
[[menu.main]]
  name = "Posts"
  weight = 2
  url  = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 3
  url  = "projects/"
[[menu.main]]
  name = "Publications"
  weight = 4
  url  = "publications/"
[[menu.main]]
  name = "Talks"
  weight = 5
  url  = "talks/"
[[menu.main]]
  name = "Stats"
  weight = 6
  url  = "https://zansaradev.goatcounter.com"
